baseURL = "/"
languageCode = "ja-jp"
title = "bellbind's trial"
paginate = "10"

[Params]
  mainSections = ["post"]
  mathjax = true

[Params.Breadcrumb]
  enable = true
  homeText = "/"

[Params.Social]
  twitter = "bellbind"
  github = "bellbind"

[outputs]
  home = ["HTML", "RSS"]

[module]
  [[module.imports]]
    path = "github.com/vimux/binario"
    