baseURL = "/"
languageCode = "ja-jp"
title = "bellbind's trial"
paginate = "10"
theme = "binario"

[Params]
  mainSections = ["post"]
  mathjax = true

[Params.Breadcrumb]
  enable = true
  homeText = "/"

[Params.Social]
  twitter = "bellbind"
  github = "bellbind"

[outputs]
  home = ["HTML", "RSS"]